config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites
	has_many :favorited_users, through: :favorites, source: :user
	has_many :book_comments
	has_many :book_commented_users, through: :book_comments, source: :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments
  has_many :book_commented_books, through: :book_comments, source: :book
  attachment :profile_image

  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@book_comment = current_user.book_comments.create(book_comment_params)
		redirect_back(fallback_location: root_path)
	end

	def destroy
		redirect_not_match_user(current_user.id)
		@book_comment = BookComment.find_by(book_id: params[:book_id], user_id: current_user.id)
		@book_comment.destroy
		redirect_back(fallback_location: root_path)
	end

	private

	def book_comment_params
		params.require(:book_comment).permit(:body).merge(book_id: params[:book_id])
	end

	def redirect_not_match_user(user_id)
		redirect_to books_path if current_user.id != user_id
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

	def index
		@books = Book.all
		@new_book = Book.new
		@user = User.find(current_user.id)
	end

	def show
		@book = Book.find(params[:id])
		@new_book = Book.new
		@user = User.find(current_user.id)
		@book_comment = BookComment.new
	end

	def create
		@new_book = Book.new(book_params)
		if @new_book.save
			flash[:success] = 'You have creatad book successfully.'
			redirect_to book_path(@new_book.id)
		else
			@books = Book.all
			render 'index'
		end
	end

	def edit
		@book = Book.find(params[:id])
		redirect_not_match_user(@book.user.id)
	end

	def update
		@book = Book.find(params[:id])
		redirect_not_match_user(@book.user.id)
		if @book.update(book_params)
			flash[:success] = 'You have updated book successfully.'
			redirect_to book_path(@book.id)
		else
			render 'edit'
		end
	end

	def destroy
		book = Book.find(params[:id])
		redirect_not_match_user(book.user.id)
		if book.destroy
			flash[:success] = 'successfully: 削除しました'
			redirect_to books_path
		else
			flash[:danger] = 'error: 削除できませんでした'
			redirect_to books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :body).merge(user_id: current_user.id)
	end

	def redirect_not_match_user(user_id)
		redirect_to books_path if current_user.id != user_id
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@favorite = current_user.favorites.create(book_id: params[:book_id])
    	redirect_back(fallback_location: root_path)
	end

	def destroy
		@favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    	@favorite.destroy
    	redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
		@new_book = Book.new
	end

	def show
		@user = User.find(params[:id])
		@books = @user.books
		@new_book = Book.new
	end

	def edit
		@user = User.find(params[:id])
		redirect_not_match_user(@user.id)
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = 'You have updated user successfully.'
			redirect_to user_path(@user.id)
		else
			render 'edit'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end

	def redirect_not_match_user(user_id)
		redirect_to user_path(current_user.id) if current_user.id != user_id
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <%= form_for @book do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="field row">
            <%= f.label :title %>
            <%= f.text_field :title, value: f.object.title, class: 'col-xs-12 book_title' %>
          </div>

          <div class="field row">
            <%= f.label :body %>
            <%= f.text_area :body, value: f.object.body, class: 'col-xs-12 book_body' %>
          </div>

          <div class="actions row">
            <%= f.submit 'Update Book', class: 'btn btn-primary col-xs-12',data: { disable_with: "Updating..." } %>
          </div>
        <% end %>
        <%= link_to 'Show', book_path(@book.id) %> |
        <%= link_to 'Back', books_path %>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <%= render partial: 'layouts/error_messages', locals: {model: @new_book} %>
    <%= render partial: 'layouts/flash_message' %>
    <div class="row">
      <%= render partial: "layouts/current_user", locals: { new_book: @new_book }%>
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td>
                  <% if current_user.already_favorited?(book) %>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <span class="glyphicon glyphicon-heart"><%= book.favorites.count %></span>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  コメント数：<%= book.book_comments.count %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <%= render partial: 'layouts/flash_message' %>
    <div class="row">
      <%= render partial: "layouts/current_user", locals: { new_book: @new_book }%>
      <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book.id) %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if current_user.already_favorited?(@book) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <span class="glyphicon glyphicon-heart"><%= @book.favorites.count %></span>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <span class="glyphicon glyphicon-heart-empty"><%= @book.favorites.count %></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= @book.book_comments.count %>
              </td>
              <% if current_user.id == @book.user.id %>
                <td>
                  <%= link_to 'Edit', edit_book_path(@book.id), class: 'btn-sm btn-success' %>
                </td>
                <td>
                  <%= link_to 'Destroy', book_path(@book.id), class: 'btn-sm btn-danger', method: :delete, data: {confirm: "本当に消しますか？"} %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <table class="show-tb">
          <tbody>
            <% @book.book_comments.each do |comment| %>
              <tr>
                <td>
                  <%= link_to user_path(comment.user.id) do %>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %><br>
                    <%= @book.user.name %>
                   <% end %>
                </td>
                <td>
                  <%= comment.body %>
                </td>
                <% if current_user.id == comment.user.id %>
                  <td>
                    <%= link_to 'Destroy', book_book_comments_path(@book.id), class: 'btn-sm btn-danger', method: :delete %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="comment-form">
          <%= form_for [@book, @book_comment] do |f| %>
            <%= f.text_area :body, :size => "90x5" %>
            <%= f.submit '送信', data: { disable_with: "送信" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
  </div>
</div>
<footer>
  <div class="container">
  	<div class="row">
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/home/top.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <%= render partial: 'layouts/flash_message' %>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
        <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper">
          <% if user_signed_in? %>
            <div class="row">
              <p>
                <%= link_to 'Log in', user_path(current_user.id), class: 'btn btn-info col-xs-10 col-xs-offset-1' %>
              </p>
            </div>
            <div class="row">
              <p>
                <%= link_to 'Sign Up', user_path(current_user.id), class: 'btn btn-success col-xs-10 col-xs-offset-1' %>
              </p>
            </div>
          <% else %>
            <div class="row">
              <p>
                <%= link_to 'Log in', new_user_session_path, class: 'btn btn-info col-xs-10 col-xs-offset-1' %>
              </p>
            </div>
            <div class="row">
              <p>
                <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success col-xs-10 col-xs-offset-1' %>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_current_user.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
      </tr>
      <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to '', edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
  </div>
  <h2>New book</h2>
  <%= form_for new_book do |f| %>
    <div class="field row">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'col-xs-12 book_title' %>
    </div>

    <div class="field row">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'col-xs-12 book_body' %>
    </div>

    <div class="actions row">
      <%= f.submit 'Create Book', class: 'btn btn-primary col-xs-12', data: { disable_with: "Creating..." } %>
    </div>
  <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= model.errors.count %> errors prohibited  data from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

<style type="text/css" media="screen">
	.alert-success {
		background-color: #90ee90;
	}

	.alert-notice {
		background-color: #add8e6;
	}

	.alert-warning {
		background-color: #f0e68c;
	}

	.alert-danger {
		background-color: #f08080;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' Home', user_path(current_user.id), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, class: 'glyphicon glyphicon-log-out logout', method: :delete %></li>
            <% else %>
              <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div id="contain">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
        <div class="image5"></div>
      </div>
    </div>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <h2>User info</h2>
    <%= form_for @user do |f| %>
      <%= render partial: 'layouts/error_messages', locals: {model: f.object} %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :profile_image %>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>

      <div class="field">
        <%= f.label :introduction %>
        <%= f.text_area :introduction %>
      </div>

      <div class="actions">
        <%= f.submit 'Update User', data: { disable_with: "Updating..." } %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <%= render partial: "layouts/current_user", locals: { new_book: @new_book }%>
      <div class="col-xs-9">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to 'Show', user_path(user.id) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <%= render partial: 'layouts/flash_message' %>
    <div class="row">
      <%= render partial: "layouts/current_user", locals: { new_book: @new_book }%>
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr> 
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>